<?php

use Illuminate\Database\Seeder;

class SystemInstallWorkflowFlowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('workflow_flows')->delete();
        
        \DB::table('workflow_flows')->insert(array (
            0 => 
            array (
                'id' => 34,
                'flow_no' => 'entry_apply',
                'flow_name' => '入职申请流程',
                'template_id' => 30,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":217,"flow_id":34,"process_name":"\\u5f00\\u59cb","process_to":"218","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:363px;top:282px;"},{"id":218,"flow_id":34,"process_name":"\\u5ba1\\u6838\\u4eba\\u4e00","process_to":"219","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:614px;top:281px;"},{"id":219,"flow_id":34,"process_name":"\\u6700\\u7ec8","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:839px;top:285px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '入职专用',
                'created_at' => '2019-04-14 16:30:28',
                'updated_at' => '2019-06-05 15:06:17',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'examineApprove?',
            ),
            1 => 
            array (
                'id' => 35,
                'flow_no' => 'fee_expense',
                'flow_name' => '报销',
                'template_id' => 31,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":220,"flow_id":35,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"221","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:72px;"},"1":{"id":221,"flow_id":35,"process_name":"\\u4e00\\u7ea7\\u9886\\u5bfc","process_to":"222","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:270px;"},"2":{"id":222,"flow_id":35,"process_name":"\\u4e8c\\u7ea7\\u9886\\u5bfc","process_to":"224","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:432px;top:487px;"},"5":{"id":224,"flow_id":35,"process_name":"\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:996px;top:487px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '财务报销流程',
                'created_at' => '2019-04-14 20:03:51',
                'updated_at' => '2019-05-17 16:12:43',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'newExpense',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'finance/flowDetails?',
            ),
            2 => 
            array (
                'id' => 36,
                'flow_no' => 'outside_punch',
                'flow_name' => '外出',
                'template_id' => 33,
                'type_id' => 3,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":225,"flow_id":36,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"226","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:318px;top:200px;"},{"id":226,"flow_id":36,"process_name":"\\u4e00\\u7ea7\\u6c47\\u62a5\\u4eba","process_to":"227","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:318px;top:305px;"},{"id":227,"flow_id":36,"process_name":"\\u4e8c\\u7ea7\\u6c47\\u62a5\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:318px;top:398px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '出差、外勤',
                'created_at' => '2019-04-15 13:58:21',
                'updated_at' => '2019-06-02 15:00:31',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq',
                'route_url' => 'besides',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'vacatedetails?title=外出&tid=36&',
            ),
            3 => 
            array (
                'id' => 37,
                'flow_no' => 'positive_apply',
                'flow_name' => '转正',
                'template_id' => 34,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":230,"flow_id":37,"process_name":"\\u5f00\\u59cb","process_to":"231","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:538px;top:351px;"},{"id":231,"flow_id":37,"process_name":"\\u5ba1\\u6838\\u4eba\\u4e00","process_to":"232","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:851px;top:352px;"},{"id":232,"flow_id":37,"process_name":"\\u6700\\u540e","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1164px;top:351px;"}]}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-15 17:23:05',
                'updated_at' => '2019-05-30 23:26:42',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-kc4',
                'route_url' => 'employeeApplicationCorrection',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'rosterTransact?',
            ),
            4 => 
            array (
                'id' => 38,
                'flow_no' => 'patch',
                'flow_name' => '补卡',
                'template_id' => 35,
                'type_id' => 3,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":233,"flow_id":38,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":"234","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:526px;top:242px;"},{"id":234,"flow_id":38,"process_name":"\\u7b2c\\u4e00\\u7ea7\\u5ba1\\u6279\\u4eba","process_to":"235","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:597px;top:349px;"},{"id":235,"flow_id":38,"process_name":"\\u7b2c\\u4e8c\\u7ea7\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:661px;top:464px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-18 09:51:35',
                'updated_at' => '2019-06-02 14:59:12',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq3',
                'route_url' => 'fill',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'vacatedetails?title=补卡&tid=38&',
            ),
            5 => 
            array (
                'id' => 39,
                'flow_no' => 'business_trip',
                'flow_name' => '出差',
                'template_id' => 36,
                'type_id' => 3,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":237,"flow_id":39,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":"238","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:481px;top:277px;"},{"id":238,"flow_id":39,"process_name":"\\u7b2c\\u4e00\\u7ea7\\u8d1f\\u8d23\\u4eba","process_to":"239","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:563px;top:371px;"},{"id":239,"flow_id":39,"process_name":"\\u7b2c\\u4e8c\\u7ea7\\u8d1f\\u8d23\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:640px;top:460px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '出差',
                'created_at' => '2019-04-18 09:51:35',
                'updated_at' => '2019-06-02 14:57:38',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-cg4',
                'route_url' => 'evection',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'vacatedetails?title=出差&tid=39&',
            ),
            6 => 
            array (
                'id' => 40,
                'flow_no' => 'leave',
                'flow_name' => '请假',
                'template_id' => 37,
                'type_id' => 3,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":241,"flow_id":40,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":"242","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:559px;top:187px;"},{"id":242,"flow_id":40,"process_name":"\\u7b2c\\u4e00\\u7ea7\\u8d1f\\u8d23\\u4eba","process_to":"243","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:575px;top:312px;"},{"id":243,"flow_id":40,"process_name":"\\u7b2c\\u4e8c\\u7ea7\\u8d1f\\u8d23\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:658px;top:409px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-18 09:51:35',
                'updated_at' => '2019-06-01 19:36:46',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq',
                'route_url' => 'Vacate',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'vacatedetails?title=请假&tid=40&',
            ),
            7 => 
            array (
                'id' => 41,
                'flow_no' => 'extra',
                'flow_name' => '加班',
                'template_id' => 38,
                'type_id' => 3,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":245,"flow_id":41,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":"246","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:490px;top:255px;"},{"id":246,"flow_id":41,"process_name":"\\u7b2c\\u4e00\\u7ea7\\u5ba1\\u6279\\u4eba","process_to":"247","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:490px;top:352px;"},{"id":247,"flow_id":41,"process_name":"\\u7b2c\\u4e8c\\u7ea7\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:490px;top:461px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '加班申请',
                'created_at' => '2019-04-18 09:51:35',
                'updated_at' => '2019-06-03 10:41:28',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-kc1',
                'route_url' => 'overtime',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'vacatedetails?title=加班&tid=41&',
            ),
            8 => 
            array (
                'id' => 42,
                'flow_no' => 'finance_loan',
                'flow_name' => '借款',
                'template_id' => 39,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":249,"flow_id":42,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"250","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:72px;"},"1":{"id":250,"flow_id":42,"process_name":"\\u4e00\\u7ea7\\u9886\\u5bfc","process_to":"251","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:270px;"},"2":{"id":251,"flow_id":42,"process_name":"\\u4e8c\\u7ea7\\u9886\\u5bfc","process_to":"253","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:432px;top:487px;"},"5":{"id":253,"flow_id":42,"process_name":"\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:996px;top:487px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '财务报销流程',
                'created_at' => '2019-04-18 19:29:17',
                'updated_at' => '2019-05-17 16:17:32',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'newExpense',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'finance/flowDetails?',
            ),
            9 => 
            array (
                'id' => 43,
                'flow_no' => 'finance_repayment',
                'flow_name' => '还款',
                'template_id' => 40,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":254,"flow_id":43,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"255","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:72px;"},"1":{"id":255,"flow_id":43,"process_name":"\\u4e00\\u7ea7\\u9886\\u5bfc","process_to":"256","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:270px;"},"2":{"id":256,"flow_id":43,"process_name":"\\u4e8c\\u7ea7\\u9886\\u5bfc","process_to":"258","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1057px;top:270px;"},"5":{"id":258,"flow_id":43,"process_name":"\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1057px;top:581px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '财务报销流程',
                'created_at' => '2019-04-18 19:29:31',
                'updated_at' => '2019-05-17 16:18:09',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'newExpense',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'finance/flowDetails?',
            ),
            10 => 
            array (
                'id' => 44,
                'flow_no' => 'finance_receivables',
                'flow_name' => '收款',
                'template_id' => 41,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":259,"flow_id":44,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"260","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:72px;"},"1":{"id":260,"flow_id":44,"process_name":"\\u4e00\\u7ea7\\u9886\\u5bfc","process_to":"261","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:270px;"},"2":{"id":261,"flow_id":44,"process_name":"\\u4e8c\\u7ea7\\u9886\\u5bfc","process_to":"263","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:432px;top:487px;"},"5":{"id":263,"flow_id":44,"process_name":"\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:996px;top:487px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '财务报销流程',
                'created_at' => '2019-04-18 19:29:44',
                'updated_at' => '2019-05-17 16:18:59',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'newExpense',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'finance/flowDetails?',
            ),
            11 => 
            array (
                'id' => 45,
                'flow_no' => 'finance_payment',
                'flow_name' => '支付',
                'template_id' => 42,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":264,"flow_id":45,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"265","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:72px;"},"1":{"id":265,"flow_id":45,"process_name":"\\u4e00\\u7ea7\\u9886\\u5bfc","process_to":"266","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:652px;top:270px;"},"2":{"id":266,"flow_id":45,"process_name":"\\u4e8c\\u7ea7\\u9886\\u5bfc","process_to":"268","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:432px;top:487px;"},"5":{"id":268,"flow_id":45,"process_name":"\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:996px;top:487px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '财务报销流程',
                'created_at' => '2019-04-18 19:29:56',
                'updated_at' => '2019-05-17 16:20:24',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'newExpense',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'finance/flowDetails?',
            ),
            12 => 
            array (
                'id' => 46,
                'flow_no' => 'positive_wage_apply',
                'flow_name' => '转正工资包流程',
                'template_id' => 43,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":269,"flow_id":46,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":"270","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:322px;top:304px;"},{"id":270,"flow_id":46,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"271","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:805px;top:320px;"},{"id":271,"flow_id":46,"process_name":"\\u6700\\u540e","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1255px;top:337px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-19 09:32:05',
                'updated_at' => '2019-05-30 23:33:44',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'rosterSalaryPackage?',
            ),
            13 => 
            array (
                'id' => 47,
                'flow_no' => 'contract_approval',
                'flow_name' => '合同审批',
                'template_id' => 44,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":{"1":{"id":272,"flow_id":47,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":"273","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:710px;top:368px;"},"2":{"id":273,"flow_id":47,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1066px;top:369px;"},"3":{"id":274,"flow_id":47,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":"272","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:237px;top:368px;"}},"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-22 10:20:45',
                'updated_at' => '2019-05-31 13:27:55',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'approver?',
            ),
            14 => 
            array (
                'id' => 48,
                'flow_no' => 'leave_handover_apply',
                'flow_name' => '离职交接单',
                'template_id' => 45,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":275,"flow_id":48,"process_name":"\\u5f00\\u59cb","process_to":"276","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:390px;top:292px;"},{"id":276,"flow_id":48,"process_name":"\\u65b0\\u5efa\\u6b65\\u9aa4","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:725px;top:290px;"}],"total":2}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-22 10:33:26',
                'updated_at' => '2019-06-02 17:58:40',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-kc3',
                'route_url' => 'employeesLeaveVoluntarily',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'turnoverHandoverContent?',
            ),
            15 => 
            array (
                'id' => 49,
                'flow_no' => 'fire_staff_apply',
                'flow_name' => '开除员工',
                'template_id' => 46,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":277,"flow_id":49,"process_name":"\\u5f00\\u59cb","process_to":"278","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:391px;top:273px;"},{"id":278,"flow_id":49,"process_name":"\\u5ba1\\u6279\\u6210\\u529f","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:687px;top:277px;"}],"total":2}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-22 10:33:27',
                'updated_at' => '2019-05-14 19:40:37',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-kc6',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            16 => 
            array (
                'id' => 50,
                'flow_no' => 'active_leave_apply',
                'flow_name' => '离职',
                'template_id' => 47,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":279,"flow_id":50,"process_name":"\\u7b2c\\u4e00\\u6b65","process_to":"280","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:459px;top:269px;"},{"id":280,"flow_id":50,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"281","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:757px;top:268px;"},{"id":281,"flow_id":50,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1041px;top:266px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-04-22 10:33:29',
                'updated_at' => '2019-06-02 17:57:51',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-sq4',
                'route_url' => 'employeesLeaveVoluntarily',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'turnoverHandoverContent?',
            ),
            17 => 
            array (
                'id' => 51,
                'flow_no' => 'official_doc',
                'flow_name' => '行政公文',
                'template_id' => 49,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":282,"flow_id":51,"process_name":"\\u53d1\\u5e03\\u4eba","process_to":"283","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:563px;top:193px;"},{"id":283,"flow_id":51,"process_name":"\\u7b7e\\u6279\\u4eba","process_to":"284","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:563px;top:299px;"},{"id":284,"flow_id":51,"process_name":"\\u516c\\u7ae0\\u7ba1\\u7406\\u5458","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:563px;top:418px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-04-26 16:32:13',
                'updated_at' => '2019-05-14 20:54:42',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 1,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            18 => 
            array (
                'id' => 52,
                'flow_no' => 'meeting_record_review',
                'flow_name' => '会议申请记录审核',
                'template_id' => 51,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":286,"flow_id":52,"process_name":"\\u4f1a\\u8bae\\u7533\\u8bf7","process_to":"287","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:513px;top:219px;"},{"id":287,"flow_id":52,"process_name":"\\u4e00\\u7ea7\\u5ba1\\u6838","process_to":"288","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:513px;top:405px;"},{"id":288,"flow_id":52,"process_name":"\\u6700\\u540e\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:513px;top:535px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '对会议进行审核',
                'created_at' => '2019-04-27 11:12:26',
                'updated_at' => '2019-05-30 22:43:31',
                'leader_link_type' => 'report',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'meetingDetails?',
            ),
            19 => 
            array (
                'id' => 53,
                'flow_no' => 'administrative_documents',
                'flow_name' => '行政文件公文流程',
                'template_id' => 52,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":289,"flow_id":53,"process_name":"\\u7b2c\\u4e00\\u6b65","process_to":"290","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:481px;top:309px;"},"1":{"id":290,"flow_id":53,"process_name":"\\u7b7e\\u6279\\u4eba","process_to":"292","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:785px;top:308px;"},"3":{"id":291,"flow_id":53,"process_name":"\\u5957\\u7ea2\\u76d6\\u7ae0","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1195px;top:367px;"},"4":{"id":292,"flow_id":53,"process_name":"\\u7b7e\\u6279\\u4eba1","process_to":"291","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:979px;top:355px;"}},"total":4}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-04-29 16:32:11',
                'updated_at' => '2019-05-14 20:53:19',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            20 => 
            array (
                'id' => 54,
                'flow_no' => 'meeting_summary',
                'flow_name' => '会议纪要审核',
                'template_id' => 51,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":293,"flow_id":54,"process_name":"\\u4f1a\\u8bae\\u7eaa\\u8981","process_to":"294","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:631px;top:145px;"},{"id":294,"flow_id":54,"process_name":"\\u4e00\\u7ea7\\u5ba1\\u6838","process_to":"295","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:746px;top:364px;"},{"id":295,"flow_id":54,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1095px;top:364px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-04-30 13:46:04',
                'updated_at' => '2019-04-30 13:57:34',
                'leader_link_type' => 'report',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'meetingDetails?',
            ),
            21 => 
            array (
                'id' => 55,
                'flow_no' => 'executive_cars',
                'flow_name' => '行政新建车辆',
                'template_id' => 53,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":296,"flow_id":55,"process_name":"\\u5f00\\u59cb","process_to":"297","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:282px;top:124px;"},{"id":297,"flow_id":55,"process_name":"\\u4e3b\\u7ba1\\u5ba1\\u6838","process_to":"298","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:488px;top:181px;"},{"id":298,"flow_id":55,"process_name":"\\u7ecf\\u7406\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:664px;top:231px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-07 13:30:00',
                'updated_at' => '2019-05-08 17:14:30',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            22 => 
            array (
                'id' => 56,
                'flow_no' => 'pas_purchase',
                'flow_name' => '进销存采购申请单',
                'template_id' => 54,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":300,"flow_id":56,"process_name":"\\u91c7\\u8d2d\\u7533\\u8bf7","process_to":"302","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:677px;top:157px;"},{"id":301,"flow_id":56,"process_name":"\\u8d22\\u52a1\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:961px;top:312px;"},{"id":302,"flow_id":56,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":"301","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:676px;top:313px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '进销存中申请采购单进行审核',
                'created_at' => '2019-05-08 17:07:50',
                'updated_at' => '2019-05-16 15:17:19',
                'leader_link_type' => 'report',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'procurementDetail?czType=c&',
            ),
            23 => 
            array (
                'id' => 57,
                'flow_no' => 'executive_cars_use',
                'flow_name' => '行政申请用车',
                'template_id' => 55,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":303,"flow_id":57,"process_name":"\\u5f00\\u59cb","process_to":"304","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:338px;top:127px;"},{"id":304,"flow_id":57,"process_name":"\\u7b2c\\u4e00\\u6b65","process_to":"305","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:416px;top:257px;"},{"id":305,"flow_id":57,"process_name":"\\u5ba1\\u6838\\u5b8c\\u6210","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:514px;top:364px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-08 18:06:37',
                'updated_at' => '2019-05-09 13:00:47',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            24 => 
            array (
                'id' => 58,
                'flow_no' => 'welfare',
                'flow_name' => '福利',
                'template_id' => 56,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":306,"flow_id":58,"process_name":"\\u798f\\u5229\\u5ba1\\u6279","process_to":307,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:438px;top:275px;"},{"id":307,"flow_id":58,"process_name":"\\u603b\\u76d1\\u5ba1\\u6279","process_to":308,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:847px;top:275px;"},{"id":308,"flow_id":58,"process_name":"\\u884c\\u653f\\u5ba1\\u6279","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1194px;top:275px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '福利发放',
                'created_at' => '2019-05-09 17:57:12',
                'updated_at' => '2019-05-14 20:56:35',
                'leader_link_type' => 'business',
                'icon_url' => '#icon-cg6',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            25 => 
            array (
                'id' => 59,
                'flow_no' => 'executive_cars_appoint',
                'flow_name' => '行政申请派车',
                'template_id' => 57,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":309,"flow_id":59,"process_name":"\\u5f00\\u59cb","process_to":"310","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:245px;top:212px;"},{"id":310,"flow_id":59,"process_name":"\\u7b2c\\u4e00\\u6b65","process_to":"311","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:481px;top:300px;"},{"id":311,"flow_id":59,"process_name":"\\u7ed3\\u675f","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:684px;top:404px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-09 18:23:32',
                'updated_at' => '2019-05-09 18:25:14',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            26 => 
            array (
                'id' => 60,
                'flow_no' => 'executive_cars_sendback',
                'flow_name' => '行政归还车辆',
                'template_id' => 58,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":312,"flow_id":60,"process_name":"\\u5f00\\u59cb","process_to":"313","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:326px;top:148px;"},{"id":313,"flow_id":60,"process_name":"\\u7b2c\\u4e00\\u6b65","process_to":"314","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:450px;top:248px;"},{"id":314,"flow_id":60,"process_name":"\\u7ed3\\u675f","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:607px;top:396px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-09 18:23:50',
                'updated_at' => '2019-05-09 18:26:27',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            27 => 
            array (
                'id' => 61,
                'flow_no' => 'intelligence_apply',
                'flow_name' => '情报',
                'template_id' => 59,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":315,"flow_id":61,"process_name":"\\u63d0\\u4ea4\\u4eba","process_to":"316","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:445px;top:263px;"},{"id":316,"flow_id":61,"process_name":"\\u7ba1\\u7406\\u5458","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:833px;top:331px;"}],"total":2}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-10 17:02:23',
                'updated_at' => '2019-05-15 10:53:58',
                'leader_link_type' => 'business',
                'icon_url' => 'icon-kc5',
                'route_url' => 'newConstruction',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            28 => 
            array (
                'id' => 62,
                'flow_no' => 'pas_return_order',
                'flow_name' => '进销存退货申请单',
                'template_id' => 60,
                'type_id' => 1,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":317,"flow_id":62,"process_name":"\\u9000\\u8d27\\u7533\\u8bf7","process_to":"318","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:692px;top:173px;"},{"id":318,"flow_id":62,"process_name":"\\u4e00\\u7ea7\\u5ba1\\u6838","process_to":"319","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:797px;top:303px;"},{"id":319,"flow_id":62,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:789px;top:431px;"}]}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-13 13:21:17',
                'updated_at' => '2019-05-17 11:59:59',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'procurementDetail?czType=t&',
            ),
            29 => 
            array (
                'id' => 63,
                'flow_no' => 'pas_sale_orders',
                'flow_name' => '进销存销售单审批',
                'template_id' => 61,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":320,"flow_id":63,"process_name":"\\u53d1\\u8d77\\u7533\\u8bf7","process_to":"321","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:465px;top:211px;"},{"id":321,"flow_id":63,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":"322","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:542px;top:353px;"},{"id":322,"flow_id":63,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:658px;top:503px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-14 10:04:22',
                'updated_at' => '2019-05-14 10:11:54',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'saleDetail?',
            ),
            30 => 
            array (
                'id' => 64,
                'flow_no' => 'pas_payment_order',
                'flow_name' => '进销存采购中的付款单',
                'template_id' => 60,
                'type_id' => 2,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":323,"flow_id":64,"process_name":"\\u4ed8\\u6b3e\\u5355\\u7533\\u8bf7","process_to":"324","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:636px;top:141px;"},{"id":324,"flow_id":64,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":"325","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:662px;top:275px;"},{"id":325,"flow_id":64,"process_name":"\\u8d22\\u52a1\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:724px;top:445px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-14 17:29:27',
                'updated_at' => '2019-05-15 13:41:48',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'procurementDetail?czType=f&',
            ),
            31 => 
            array (
                'id' => 65,
                'flow_no' => 'inspector_apply',
                'flow_name' => '反馈',
                'template_id' => 62,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":{"0":{"id":326,"flow_id":65,"process_name":"\\u5f00\\u59cb","process_to":"328","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:553px;top:294px;"},"2":{"id":328,"flow_id":65,"process_name":"\\u7ba1\\u7406\\u5458","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1185px;top:334px;"}},"total":2}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-15 10:53:16',
                'updated_at' => '2019-05-15 11:40:24',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            32 => 
            array (
                'id' => 66,
                'flow_no' => 'pas_sale_return_orders',
                'flow_name' => '进销存销售退货单审批',
                'template_id' => 63,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"total":3,"list":[{"id":329,"flow_id":66,"process_name":"\\u53d1\\u8d77\\u7533\\u8bf7","process_to":"330","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:438px;top:311px;"},{"id":330,"flow_id":66,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":"331","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:602px;top:409px;"},{"id":331,"flow_id":66,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:682px;top:631px;"}]}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-17 11:24:16',
                'updated_at' => '2019-05-17 11:29:59',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => 'returnDetails?',
            ),
            33 => 
            array (
                'id' => 67,
                'flow_no' => 'corporate_assets_borrow',
                'flow_name' => '公司资产借用',
                'template_id' => 64,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":333,"flow_id":67,"process_name":"\\u501f\\u7528\\u4eba","process_to":334,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:516px;top:346px;"},{"id":334,"flow_id":67,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":335,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:788px;top:326px;"},{"id":335,"flow_id":67,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1154px;top:337px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:13:55',
                'updated_at' => '2019-05-31 11:13:55',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            34 => 
            array (
                'id' => 68,
                'flow_no' => 'corporate_assets_return',
                'flow_name' => '公司资产归还',
                'template_id' => 65,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":336,"flow_id":68,"process_name":"\\u5f52\\u8fd8\\u4eba","process_to":337,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:726px;top:367px;"},{"id":337,"flow_id":68,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":338,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1014px;top:377px;"},{"id":338,"flow_id":68,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1233px;top:409px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:14:07',
                'updated_at' => '2019-05-31 11:14:07',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            35 => 
            array (
                'id' => 69,
                'flow_no' => 'corporate_assets_transfer',
                'flow_name' => '公司资产调拨',
                'template_id' => 66,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":339,"flow_id":69,"process_name":"\\u53d1\\u8d77\\u4eba","process_to":340,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:631px;top:314px;"},{"id":340,"flow_id":69,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":341,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:943px;top:320px;"},{"id":341,"flow_id":69,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1324px;top:416px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:14:23',
                'updated_at' => '2019-05-31 11:14:23',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            36 => 
            array (
                'id' => 70,
                'flow_no' => 'corporate_assets_repair',
                'flow_name' => '公司资产送修',
                'template_id' => 67,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":342,"flow_id":70,"process_name":"\\u9001\\u4fee\\u4eba","process_to":343,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:804px;top:382px;"},{"id":343,"flow_id":70,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":344,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1027px;top:395px;"},{"id":344,"flow_id":70,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1382px;top:477px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:14:33',
                'updated_at' => '2019-05-31 11:14:33',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            37 => 
            array (
                'id' => 71,
                'flow_no' => 'corporate_assets_scrapped',
                'flow_name' => '公司资产报废',
                'template_id' => 68,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":345,"flow_id":71,"process_name":"\\u62a5\\u5e9f\\u4eba","process_to":346,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:944px;top:242px;"},{"id":346,"flow_id":71,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":347,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:696px;top:525px;"},{"id":347,"flow_id":71,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1323px;top:484px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:14:42',
                'updated_at' => '2019-05-31 11:14:42',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            38 => 
            array (
                'id' => 72,
                'flow_no' => 'corporate_assets_valueadded',
                'flow_name' => '公司资产增值',
                'template_id' => 69,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":348,"flow_id":72,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":349,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:419px;top:225px;"},{"id":349,"flow_id":72,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":350,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:819px;top:292px;"},{"id":350,"flow_id":72,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1388px;top:298px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:14:51',
                'updated_at' => '2019-05-31 11:14:51',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            39 => 
            array (
                'id' => 73,
                'flow_no' => 'corporate_assets_depreciation',
                'flow_name' => '公司资产折旧',
                'template_id' => 70,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":351,"flow_id":73,"process_name":"\\u7533\\u8bf7\\u4eba","process_to":352,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:648px;top:326px;"},{"id":352,"flow_id":73,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":353,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:813px;top:474px;"},{"id":353,"flow_id":73,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1300px;top:370px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:15:09',
                'updated_at' => '2019-05-31 11:15:09',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            40 => 
            array (
                'id' => 74,
                'flow_no' => 'corporate_assets_use',
                'flow_name' => '公司资产领用',
                'template_id' => 71,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":354,"flow_id":74,"process_name":"\\u9886\\u7528\\u4eba","process_to":355,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:723px;top:303px;"},{"id":355,"flow_id":74,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":356,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:723px;top:455px;"},{"id":356,"flow_id":74,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:970px;top:455px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:15:22',
                'updated_at' => '2019-05-31 11:15:22',
                'leader_link_type' => 'business',
                'icon_url' => NULL,
                'route_url' => NULL,
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            41 => 
            array (
                'id' => 75,
                'flow_no' => 'pas_sale_out_warehouse',
                'flow_name' => '进销存销售出库单审批',
                'template_id' => 72,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":357,"flow_id":75,"process_name":"\\u53d1\\u8d77\\u7533\\u8bf7","process_to":358,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:395px;top:150px;"},{"id":358,"flow_id":75,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":359,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:615px;top:313px;"},{"id":359,"flow_id":75,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:840px;top:487px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-31 11:17:56',
                'updated_at' => '2019-05-31 11:17:56',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            42 => 
            array (
                'id' => 76,
                'flow_no' => 'official_contract',
                'flow_name' => '行政合同',
                'template_id' => 73,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":360,"flow_id":76,"process_name":"\\u5f00\\u59cb","process_to":361,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:392px;top:345px;"},{"id":361,"flow_id":76,"process_name":"\\u5ba1\\u6279\\u4eba","process_to":362,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:916px;top:349px;"},{"id":362,"flow_id":76,"process_name":"\\u5ba1\\u6838\\u4eba","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:1294px;top:365px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 1,
                'introduction' => '',
                'created_at' => '2019-05-31 11:18:13',
                'updated_at' => '2019-05-31 11:18:13',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            43 => 
            array (
                'id' => 77,
                'flow_no' => 'pas_sale_return_in_warehouse',
                'flow_name' => '进销存销售退货入库单审批',
                'template_id' => 74,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":363,"flow_id":77,"process_name":"\\u53d1\\u8d77\\u7533\\u8bf7","process_to":364,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:320px;top:234px;"},{"id":364,"flow_id":77,"process_name":"\\u90e8\\u95e8\\u5ba1\\u6838","process_to":365,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:544px;top:380px;"},{"id":365,"flow_id":77,"process_name":"\\u6700\\u7ec8\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:797px;top:508px;"}],"total":3}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-31 11:18:28',
                'updated_at' => '2019-05-31 11:18:28',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
            44 => 
            array (
                'id' => 78,
                'flow_no' => 'meeting_room',
                'flow_name' => '会议室申请',
                'template_id' => 75,
                'type_id' => 4,
                'flowchart' => '',
                'jsplumb' => '{"list":[{"id":366,"flow_id":78,"process_name":"\\u4f1a\\u8bae\\u5ba4\\u7533\\u8bf7","process_to":367,"icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:717px;top:186px;"},{"id":367,"flow_id":78,"process_name":"\\u5ba1\\u6838","process_to":"","icon":null,"style":"width:30px;height:30px;line-height:30px;color:#78a300;left:730px;top:355px;"}],"total":2}',
                'is_publish' => 1,
                'is_show' => 0,
                'introduction' => '',
                'created_at' => '2019-05-31 11:18:38',
                'updated_at' => '2019-05-31 11:18:38',
                'leader_link_type' => 'business',
                'icon_url' => '',
                'route_url' => '',
                'version' => 0,
                'is_abandon' => 0,
                'can_view_users' => NULL,
                'can_view_departments' => NULL,
                'show_route_url' => '',
            ),
        ));
        
        
    }
}