<?php

use Illuminate\Database\Seeder;

class SystemInstallAbilitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('abilities')->delete();
        
        \DB::table('abilities')->insert(array (
            0 => 
            array (
                'id' => 8532,
                'name' => 'users_setting_create',
                'title' => '员工信息设置-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 5,
                'level2_no' => 51,
                'level3_no' => 511,
                'root_code' => 'plain',
            ),
            1 => 
            array (
                'id' => 8533,
                'name' => 'users_setting_edit',
                'title' => '员工信息设置-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 5,
                'level2_no' => 51,
                'level3_no' => 511,
                'root_code' => 'plain',
            ),
            2 => 
            array (
                'id' => 8534,
                'name' => 'users_setting_delete',
                'title' => '员工信息设置-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 5,
                'level2_no' => 51,
                'level3_no' => 511,
                'root_code' => 'plain',
            ),
            3 => 
            array (
                'id' => 8535,
                'name' => 'users_setting_show',
                'title' => '员工信息设置-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 5,
                'level2_no' => 51,
                'level3_no' => 511,
                'root_code' => 'plain',
            ),
            4 => 
            array (
                'id' => 8536,
                'name' => 'workflow_apply_show',
                'title' => '流程申请-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 711,
                'root_code' => 'mine',
            ),
            5 => 
            array (
                'id' => 8537,
                'name' => 'workflow_apply_edit',
                'title' => '流程申请-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 711,
                'root_code' => 'mine',
            ),
            6 => 
            array (
                'id' => 8538,
                'name' => 'toDoList_show',
                'title' => '待办事项-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 712,
                'root_code' => 'mine',
            ),
            7 => 
            array (
                'id' => 8539,
                'name' => 'authorize_agent_create',
                'title' => '授权审批-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 713,
                'root_code' => 'mine',
            ),
            8 => 
            array (
                'id' => 8540,
                'name' => 'authorize_agent_edit',
                'title' => '授权审批-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 713,
                'root_code' => 'mine',
            ),
            9 => 
            array (
                'id' => 8541,
                'name' => 'authorize_agent_delete',
                'title' => '授权审批-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 713,
                'root_code' => 'mine',
            ),
            10 => 
            array (
                'id' => 8542,
                'name' => 'authorize_agent_show',
                'title' => '授权审批-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 713,
                'root_code' => 'mine',
            ),
            11 => 
            array (
                'id' => 8543,
                'name' => 'processQuery_show',
                'title' => '流程查询-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 71,
                'level3_no' => 714,
                'root_code' => 'mine',
            ),
            12 => 
            array (
                'id' => 8544,
                'name' => 'myAttendance_show',
                'title' => '我的考勤-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 72,
                'level3_no' => 721,
                'root_code' => 'mine',
            ),
            13 => 
            array (
                'id' => 8545,
                'name' => 'vacation_show',
                'title' => '我的假期-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 72,
                'level3_no' => 722,
                'root_code' => 'mine',
            ),
            14 => 
            array (
                'id' => 8546,
                'name' => 'leader_show',
                'title' => '部门统计-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 7,
                'level2_no' => 72,
                'level3_no' => 723,
                'root_code' => 'mine',
            ),
            15 => 
            array (
                'id' => 8547,
                'name' => 'deptdepart_create',
                'title' => '部门管理列表-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 81,
                'level3_no' => 811,
                'root_code' => 'hr',
            ),
            16 => 
            array (
                'id' => 8548,
                'name' => 'deptdepart_delete',
                'title' => '部门管理列表-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 81,
                'level3_no' => 811,
                'root_code' => 'hr',
            ),
            17 => 
            array (
                'id' => 8549,
                'name' => 'deptdepart_edit',
                'title' => '部门管理列表-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 81,
                'level3_no' => 811,
                'root_code' => 'hr',
            ),
            18 => 
            array (
                'id' => 8550,
                'name' => 'deptdepart_show',
                'title' => '部门管理列表-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 81,
                'level3_no' => 811,
                'root_code' => 'hr',
            ),
            19 => 
            array (
                'id' => 8551,
                'name' => 'users_create',
                'title' => '花名册-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            20 => 
            array (
                'id' => 8552,
                'name' => 'users_delete',
                'title' => '花名册-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            21 => 
            array (
                'id' => 8553,
                'name' => 'users_edit',
                'title' => '花名册-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            22 => 
            array (
                'id' => 8554,
                'name' => 'users_show',
                'title' => '花名册-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            23 => 
            array (
                'id' => 8555,
                'name' => 'users_dimission',
                'title' => '花名册-离职',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            24 => 
            array (
                'id' => 8556,
                'name' => 'users_export',
                'title' => '花名册-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 821,
                'root_code' => 'hr',
            ),
            25 => 
            array (
                'id' => 8557,
                'name' => 'pendingusers_create',
                'title' => '待入职管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 822,
                'root_code' => 'hr',
            ),
            26 => 
            array (
                'id' => 8558,
                'name' => 'pendingusers_delete',
                'title' => '待入职管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 822,
                'root_code' => 'hr',
            ),
            27 => 
            array (
                'id' => 8559,
                'name' => 'pendingusers_edit',
                'title' => '待入职管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 822,
                'root_code' => 'hr',
            ),
            28 => 
            array (
                'id' => 8560,
                'name' => 'pendingusers_show',
                'title' => '待入职管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 822,
                'root_code' => 'hr',
            ),
            29 => 
            array (
                'id' => 8561,
                'name' => 'pendingusers_join',
                'title' => '待入职管理-入职',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 822,
                'root_code' => 'hr',
            ),
            30 => 
            array (
                'id' => 8562,
                'name' => 'departments_create',
                'title' => '人事地图-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 823,
                'root_code' => 'hr',
            ),
            31 => 
            array (
                'id' => 8563,
                'name' => 'departments_delete',
                'title' => '人事地图-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 823,
                'root_code' => 'hr',
            ),
            32 => 
            array (
                'id' => 8564,
                'name' => 'departments_edit',
                'title' => '人事地图-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 823,
                'root_code' => 'hr',
            ),
            33 => 
            array (
                'id' => 8565,
                'name' => 'departments_show',
                'title' => '人事地图-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 823,
                'root_code' => 'hr',
            ),
            34 => 
            array (
                'id' => 8566,
                'name' => 'stats_show',
                'title' => '入离职统计-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 82,
                'level3_no' => 824,
                'root_code' => 'hr',
            ),
            35 => 
            array (
                'id' => 8567,
                'name' => 'attendance_show',
                'title' => '考勤管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 831,
                'root_code' => 'hr',
            ),
            36 => 
            array (
                'id' => 8568,
                'name' => 'attendance_edit',
                'title' => '考勤管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 831,
                'root_code' => 'hr',
            ),
            37 => 
            array (
                'id' => 8569,
                'name' => 'duty_show',
                'title' => '班值管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 832,
                'root_code' => 'hr',
            ),
            38 => 
            array (
                'id' => 8570,
                'name' => 'duty_create',
                'title' => '班值管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 832,
                'root_code' => 'hr',
            ),
            39 => 
            array (
                'id' => 8571,
                'name' => 'duty_edit',
                'title' => '班值管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 832,
                'root_code' => 'hr',
            ),
            40 => 
            array (
                'id' => 8572,
                'name' => 'duty_delete',
                'title' => '班值管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 832,
                'root_code' => 'hr',
            ),
            41 => 
            array (
                'id' => 8573,
                'name' => 'appoint_show',
                'title' => '排班管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 833,
                'root_code' => 'hr',
            ),
            42 => 
            array (
                'id' => 8574,
                'name' => 'appoint_appoint',
                'title' => '排班管理-排班',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 833,
                'root_code' => 'hr',
            ),
            43 => 
            array (
                'id' => 8575,
                'name' => 'vacationManage_show',
                'title' => '员工假期管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 834,
                'root_code' => 'hr',
            ),
            44 => 
            array (
                'id' => 8576,
                'name' => 'vacationManage_create',
                'title' => '员工假期管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 834,
                'root_code' => 'hr',
            ),
            45 => 
            array (
                'id' => 8577,
                'name' => 'vacationManage_export',
                'title' => '员工假期管理-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 834,
                'root_code' => 'hr',
            ),
            46 => 
            array (
                'id' => 8578,
                'name' => 'holiday_show',
                'title' => '节假日管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 835,
                'root_code' => 'hr',
            ),
            47 => 
            array (
                'id' => 8579,
                'name' => 'holiday_create',
                'title' => '节假日管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 835,
                'root_code' => 'hr',
            ),
            48 => 
            array (
                'id' => 8580,
                'name' => 'holiday_export',
                'title' => '节假日管理-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 835,
                'root_code' => 'hr',
            ),
            49 => 
            array (
                'id' => 8581,
                'name' => 'holiday_edit',
                'title' => '节假日管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 835,
                'root_code' => 'hr',
            ),
            50 => 
            array (
                'id' => 8582,
                'name' => 'white_show',
                'title' => '白名单-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 836,
                'root_code' => 'hr',
            ),
            51 => 
            array (
                'id' => 8583,
                'name' => 'white_create',
                'title' => '白名单-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 836,
                'root_code' => 'hr',
            ),
            52 => 
            array (
                'id' => 8584,
                'name' => 'white_delete',
                'title' => '白名单-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 836,
                'root_code' => 'hr',
            ),
            53 => 
            array (
                'id' => 8585,
                'name' => 'salary_show',
                'title' => '考勤统计-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 837,
                'root_code' => 'hr',
            ),
            54 => 
            array (
                'id' => 8586,
                'name' => 'salary_export',
                'title' => '考勤统计-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 837,
                'root_code' => 'hr',
            ),
            55 => 
            array (
                'id' => 8587,
                'name' => 'closing_show',
                'title' => '考勤关账-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 838,
                'root_code' => 'hr',
            ),
            56 => 
            array (
                'id' => 8588,
                'name' => 'closing_edit',
                'title' => '考勤关账-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 838,
                'root_code' => 'hr',
            ),
            57 => 
            array (
                'id' => 8589,
                'name' => 'closingRecord_show',
                'title' => '考勤关账记录-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 83,
                'level3_no' => 839,
                'root_code' => 'hr',
            ),
            58 => 
            array (
                'id' => 8590,
                'name' => 'approval_show',
                'title' => '审批-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 84,
                'level3_no' => 842,
                'root_code' => 'hr',
            ),
            59 => 
            array (
                'id' => 8591,
                'name' => 'salary_base_show',
                'title' => '基础薪酬-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 851,
                'root_code' => 'hr',
            ),
            60 => 
            array (
                'id' => 8592,
                'name' => 'salary_accounts_show',
                'title' => '薪酬核算-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 852,
                'root_code' => 'hr',
            ),
            61 => 
            array (
                'id' => 8593,
                'name' => 'salary_accounts_create',
                'title' => '薪酬核算-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 852,
                'root_code' => 'hr',
            ),
            62 => 
            array (
                'id' => 8594,
                'name' => 'salary_accounts_import',
                'title' => '薪酬核算-导入',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 852,
                'root_code' => 'hr',
            ),
            63 => 
            array (
                'id' => 8595,
                'name' => 'salary_accounts_export',
                'title' => '薪酬核算-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 852,
                'root_code' => 'hr',
            ),
            64 => 
            array (
                'id' => 8596,
                'name' => 'salary_accounts_delete',
                'title' => '薪酬核算-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 852,
                'root_code' => 'hr',
            ),
            65 => 
            array (
                'id' => 8597,
                'name' => 'full_payroll_show',
                'title' => '工资单关账记录-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 853,
                'root_code' => 'hr',
            ),
            66 => 
            array (
                'id' => 8598,
                'name' => 'full_payroll_create',
                'title' => '工资单关账记录-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 853,
                'root_code' => 'hr',
            ),
            67 => 
            array (
                'id' => 8599,
                'name' => 'full_payroll_import',
                'title' => '工资单关账记录-导入',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 853,
                'root_code' => 'hr',
            ),
            68 => 
            array (
                'id' => 8600,
                'name' => 'full_payroll_delete',
                'title' => '工资单关账记录-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 8,
                'level2_no' => 85,
                'level3_no' => 853,
                'root_code' => 'hr',
            ),
            69 => 
            array (
                'id' => 8601,
                'name' => 'companies_create',
                'title' => '企业信息-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            70 => 
            array (
                'id' => 8602,
                'name' => 'companies_delete',
                'title' => '企业信息-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            71 => 
            array (
                'id' => 8603,
                'name' => 'companies_edit',
                'title' => '企业信息-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            72 => 
            array (
                'id' => 8604,
                'name' => 'companies_show',
                'title' => '企业信息-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            73 => 
            array (
                'id' => 8605,
                'name' => 'companies_shareholder',
                'title' => '企业信息-股东',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            74 => 
            array (
                'id' => 8606,
                'name' => 'companies_personnel',
                'title' => '企业信息-主要人员',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            75 => 
            array (
                'id' => 8607,
                'name' => 'companies_pledge',
                'title' => '企业信息-股权',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 91,
                'level3_no' => 911,
                'root_code' => 'legal',
            ),
            76 => 
            array (
                'id' => 8608,
                'name' => 'contracts_show',
                'title' => '合同管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 92,
                'level3_no' => 921,
                'root_code' => 'legal',
            ),
            77 => 
            array (
                'id' => 8609,
                'name' => 'contracts_edit',
                'title' => '合同管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 92,
                'level3_no' => 921,
                'root_code' => 'legal',
            ),
            78 => 
            array (
                'id' => 8610,
                'name' => 'sealManage_show',
                'title' => '印章管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 93,
                'level3_no' => 931,
                'root_code' => 'legal',
            ),
            79 => 
            array (
                'id' => 8611,
                'name' => 'sealManage_create',
                'title' => '印章管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 93,
                'level3_no' => 931,
                'root_code' => 'legal',
            ),
            80 => 
            array (
                'id' => 8612,
                'name' => 'sealManage_export',
                'title' => '印章管理-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 9,
                'level2_no' => 93,
                'level3_no' => 931,
                'root_code' => 'legal',
            ),
            81 => 
            array (
                'id' => 8613,
                'name' => 'finance_yz_show',
                'title' => '分公司审批-云智-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 1011,
                'root_code' => 'finance',
            ),
            82 => 
            array (
                'id' => 8614,
                'name' => 'finance_yq_show',
                'title' => '分公司审批-云桥-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 1012,
                'root_code' => 'finance',
            ),
            83 => 
            array (
                'id' => 8615,
                'name' => 'finance_qnn_show',
                'title' => '分公司审批-钱牛牛-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 1012,
                'root_code' => 'finance',
            ),
            84 => 
            array (
                'id' => 8616,
                'name' => 'finance_relation_maintain_show',
                'title' => '分公司关系维护-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 10100,
                'root_code' => 'finance',
            ),
            85 => 
            array (
                'id' => 8617,
                'name' => 'finance_relation_maintain_export',
                'title' => '分公司关系维护-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 10100,
                'root_code' => 'finance',
            ),
            86 => 
            array (
                'id' => 8618,
                'name' => 'finance_relation_maintain_import',
                'title' => '分公司关系维护-导入',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 10,
                'level2_no' => 101,
                'level3_no' => 10100,
                'root_code' => 'finance',
            ),
            87 => 
            array (
                'id' => 8619,
                'name' => 'overview_show',
                'title' => '资产概况-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1111,
                'root_code' => 'assets',
            ),
            88 => 
            array (
                'id' => 8620,
                'name' => 'assets_show',
                'title' => '资产列表-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1112,
                'root_code' => 'assets',
            ),
            89 => 
            array (
                'id' => 8621,
                'name' => 'assets_create',
                'title' => '资产列表-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1112,
                'root_code' => 'assets',
            ),
            90 => 
            array (
                'id' => 8622,
                'name' => 'assets_edit',
                'title' => '资产列表-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1112,
                'root_code' => 'assets',
            ),
            91 => 
            array (
                'id' => 8623,
                'name' => 'assets_delete',
                'title' => '资产列表-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1112,
                'root_code' => 'assets',
            ),
            92 => 
            array (
                'id' => 8624,
                'name' => 'assets_types_show',
                'title' => '类型管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1113,
                'root_code' => 'assets',
            ),
            93 => 
            array (
                'id' => 8625,
                'name' => 'assets_types_create',
                'title' => '类型管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1113,
                'root_code' => 'assets',
            ),
            94 => 
            array (
                'id' => 8626,
                'name' => 'assets_types_edit',
                'title' => '类型管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1113,
                'root_code' => 'assets',
            ),
            95 => 
            array (
                'id' => 8627,
                'name' => 'assets_types_delete',
                'title' => '类型管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1113,
                'root_code' => 'assets',
            ),
            96 => 
            array (
                'id' => 8628,
                'name' => 'warehouse_warrant_show',
                'title' => '入库单管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 11,
                'level2_no' => 111,
                'level3_no' => 1114,
                'root_code' => 'assets',
            ),
            97 => 
            array (
                'id' => 8629,
                'name' => 'departmentMapCentre_show',
                'title' => '成本中心-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 124,
                'level3_no' => 1241,
                'root_code' => 'system',
            ),
            98 => 
            array (
                'id' => 8630,
                'name' => 'message_template_show',
                'title' => '消息模板-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            99 => 
            array (
                'id' => 8631,
                'name' => 'message_template_create',
                'title' => '消息模板-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            100 => 
            array (
                'id' => 8632,
                'name' => 'message_template_delete',
                'title' => '消息模板-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            101 => 
            array (
                'id' => 8633,
                'name' => 'message_template_edit',
                'title' => '消息模板-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            102 => 
            array (
                'id' => 8634,
                'name' => 'message_template_import',
                'title' => '消息模板-导入',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            103 => 
            array (
                'id' => 8635,
                'name' => 'message_template_export',
                'title' => '消息模板-导出',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 12,
                'level2_no' => 125,
                'level3_no' => 1251,
                'root_code' => 'system',
            ),
            104 => 
            array (
                'id' => 8636,
                'name' => 'flow_manage_create',
                'title' => '流程管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 131,
                'level3_no' => 1311,
                'root_code' => 'workflow',
            ),
            105 => 
            array (
                'id' => 8637,
                'name' => 'flow_manage_edit',
                'title' => '流程管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 131,
                'level3_no' => 1311,
                'root_code' => 'workflow',
            ),
            106 => 
            array (
                'id' => 8638,
                'name' => 'flow_manage_delete',
                'title' => '流程管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 131,
                'level3_no' => 1311,
                'root_code' => 'workflow',
            ),
            107 => 
            array (
                'id' => 8639,
                'name' => 'flow_manage_show',
                'title' => '流程管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 131,
                'level3_no' => 1311,
                'root_code' => 'workflow',
            ),
            108 => 
            array (
                'id' => 8640,
                'name' => 'template_manage_create',
                'title' => '模板管理-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 132,
                'level3_no' => 1321,
                'root_code' => 'workflow',
            ),
            109 => 
            array (
                'id' => 8641,
                'name' => 'template_manage_edit',
                'title' => '模板管理-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 132,
                'level3_no' => 1321,
                'root_code' => 'workflow',
            ),
            110 => 
            array (
                'id' => 8642,
                'name' => 'template_manage_delete',
                'title' => '模板管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 132,
                'level3_no' => 1321,
                'root_code' => 'workflow',
            ),
            111 => 
            array (
                'id' => 8643,
                'name' => 'template_manage_show',
                'title' => '模板管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 132,
                'level3_no' => 1321,
                'root_code' => 'workflow',
            ),
            112 => 
            array (
                'id' => 8644,
                'name' => 'workflow_role_create',
                'title' => '审批角色-增加',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 133,
                'level3_no' => 1331,
                'root_code' => 'workflow',
            ),
            113 => 
            array (
                'id' => 8645,
                'name' => 'workflow_role_edit',
                'title' => '审批角色-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 133,
                'level3_no' => 1331,
                'root_code' => 'workflow',
            ),
            114 => 
            array (
                'id' => 8646,
                'name' => 'workflow_role_delete',
                'title' => '审批角色-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 133,
                'level3_no' => 1331,
                'root_code' => 'workflow',
            ),
            115 => 
            array (
                'id' => 8647,
                'name' => 'workflow_role_show',
                'title' => '审批角色-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 133,
                'level3_no' => 1331,
                'root_code' => 'workflow',
            ),
            116 => 
            array (
                'id' => 8648,
                'name' => 'workflow_manager_delete',
                'title' => '审批管理-删除',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 134,
                'level3_no' => 1341,
                'root_code' => 'workflow',
            ),
            117 => 
            array (
                'id' => 8649,
                'name' => 'workflow_manager_show',
                'title' => '审批管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 13,
                'level2_no' => 134,
                'level3_no' => 1341,
                'root_code' => 'workflow',
            ),
            118 => 
            array (
                'id' => 8650,
                'name' => 'developer_index_show',
                'title' => '研发管理-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 14,
                'level2_no' => 141,
                'level3_no' => 1411,
                'root_code' => 'developer',
            ),
            119 => 
            array (
                'id' => 8651,
                'name' => 'developer_apps_show',
                'title' => '申请应用-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 14,
                'level2_no' => 142,
                'level3_no' => 1421,
                'root_code' => 'developer',
            ),
            120 => 
            array (
                'id' => 8652,
                'name' => 'monitor_task_show',
                'title' => 'task任务-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 15,
                'level2_no' => 151,
                'level3_no' => 1511,
                'root_code' => 'monitor',
            ),
            121 => 
            array (
                'id' => 8653,
                'name' => 'monitor_task_edit',
                'title' => 'task任务-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 15,
                'level2_no' => 151,
                'level3_no' => 1511,
                'root_code' => 'monitor',
            ),
            122 => 
            array (
                'id' => 8654,
                'name' => 'monitor_queue_show',
                'title' => '失败队列-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 15,
                'level2_no' => 152,
                'level3_no' => 1521,
                'root_code' => 'monitor',
            ),
            123 => 
            array (
                'id' => 8655,
                'name' => 'monitor_queue_edit',
                'title' => '失败队列-编辑',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 15,
                'level2_no' => 152,
                'level3_no' => 1521,
                'root_code' => 'monitor',
            ),
            124 => 
            array (
                'id' => 8656,
                'name' => 'monitor_jobs_show',
                'title' => '失败队列-查看',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 15,
                'level2_no' => 153,
                'level3_no' => 1531,
                'root_code' => 'monitor',
            ),
            125 => 
            array (
                'id' => 8657,
                'name' => 'leader_export',
                'title' => 'Leader export',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:58:04',
                'updated_at' => '2019-04-01 23:58:04',
                'level1_no' => 0,
                'level2_no' => 0,
                'level3_no' => 0,
                'root_code' => '',
            ),
            126 => 
            array (
                'id' => 8658,
                'name' => 'users.wx_setPassword',
                'title' => 'Users.wx set password',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:58:04',
                'updated_at' => '2019-04-01 23:58:04',
                'level1_no' => 0,
                'level2_no' => 0,
                'level3_no' => 0,
                'root_code' => '',
            ),
            127 => 
            array (
                'id' => 8659,
                'name' => 'users.wx_setPassword.reset',
                'title' => 'Users.wx set password.reset',
                'entity_id' => NULL,
                'entity_type' => NULL,
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:58:04',
                'updated_at' => '2019-04-01 23:58:04',
                'level1_no' => 0,
                'level2_no' => 0,
                'level3_no' => 0,
                'root_code' => '',
            ),
            128 => 
            array (
                'id' => 8660,
                'name' => 'basic_index',
                'title' => '基础配置-查看',
                'entity_id' => NULL,
                'entity_type' => '',
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 16,
                'level2_no' => 161,
                'level3_no' => 0,
                'root_code' => 'systems',
            ),
            129 => 
            array (
                'id' => 8661,
                'name' => 'basic_update',
                'title' => '基础配置-修改',
                'entity_id' => NULL,
                'entity_type' => '',
                'only_owned' => 0,
                'scope' => NULL,
                'created_at' => '2019-04-01 23:57:56',
                'updated_at' => '2019-04-01 23:57:56',
                'level1_no' => 16,
                'level2_no' => 161,
                'level3_no' => 0,
                'root_code' => 'systems',
            ),
        ));
        
        
    }
}