<?php

namespace App\Jobs;

use EasyWeChat\Kernel\Messages\TextCard;
use Exception;

class QueueWeChat extends BaseQueue
{

    public $order = self::QUEUE_ORDER_HIGH_THREE;

    protected $info;

    /**
     * @throws Exception
     */
    public function handle()
    {
        $mes        = $this->getArguments() ?? $this->info;
        $this->work = app('wechat.work.agent');

        if (isset($mes['url']) && !empty($mes['url'])) {
            $message['title']       = $mes['title'];
            $message['description'] = $mes['content'];
            $message['url']         = $mes['url'] ?? config('app.url');
            $messageWeChat          = new TextCard($message);
            $this->work
                ->messenger
                ->message($messageWeChat)
                ->ofAgent(env('WECHAT_WORK_AGENT_ID'))
                ->toUser($mes['receiver'])
                ->send();
        } else {
            $this->work
                ->messenger
                ->ofAgent(env('WECHAT_WORK_AGENT_ID'))
                ->toUser($mes['receiver'])
                ->send($mes['content']);
        }
    }

    public function failed(Exception $exception)
    {
        parent::failed($exception); // TODO: Change the autogenerated stub
    }
}
